# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1409406372);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1409406492);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1409492411);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1409406252);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1409492532);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20140722064054");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20140722064054");
user_pref("browser.startup.homepage_override.mstone", "31.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":3}");
user_pref("browser.uitour.whitelist.add.260", "");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1409406442226");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1409406442949");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1409492842949");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1406849541686");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1406878401673");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1406791277403");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.firstPaint", 7071);
user_pref("datareporting.sessions.current.main", 1998);
user_pref("datareporting.sessions.current.sessionRestored", 7495);
user_pref("datareporting.sessions.current.startTime", "1409539994927");
user_pref("datareporting.sessions.current.totalTime", 27);
user_pref("datareporting.sessions.currentIndex", 29);
user_pref("datareporting.sessions.previous.28", "{\"s\":1408628284481,\"a\":10,\"t\":608295,\"c\":false,\"m\":2298,\"fp\":6404,\"sr\":6897}");
user_pref("datareporting.sessions.prunedIndex", 27);
user_pref("extensions.blocklist.pingCountTotal", 21);
user_pref("extensions.blocklist.pingCountVersion", 21);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20140527.01.3");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1406012297000,\"rdfTime\":1406012265000}}}]");
user_pref("extensions.lastAppVersion", "31.0");
user_pref("extensions.lastPlatformVersion", "31.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20140722064054");
user_pref("gecko.mstone", "31.0");
user_pref("idle.lastDailyNotification", 1409492603);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1409406442);
user_pref("places.history.expiration.transient_current_max_pages", 103740);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1406877914);
user_pref("toolkit.startup.last_success", 1409539996);
user_pref("toolkit.telemetry.previousBuildID", "20140722064054");
